SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT C.CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    WHERE MONTH(C.START_DATE) BETWEEN 8 AND 10
    GROUP BY C.CAR_ID 
    HAVING COUNT(C.CAR_ID) >=5
) AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC