SELECT FP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) MFP ON FP.CATEGORY = MFP.CATEGORY AND FP.PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC