SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UU
JOIN USED_GOODS_BOARD UB ON UU.USER_ID = UB.WRITER_ID
WHERE STATUS = 'DONE'
GROUP BY UB.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES