SELECT ID, GENOTYPE, PARENT_GENOTYPE
FROM (
    SELECT ED.ID, ED.GENOTYPE, PD.GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA ED
    JOIN ECOLI_DATA PD
    ON ED.PARENT_ID = PD.ID
) AS T
WHERE GENOTYPE & PARENT_GENOTYPE = PARENT_GENOTYPE
ORDER BY ID