SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE TIME(DATETIME) BETWEEN '09:00:00' AND '19:59:00'
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY TIME(DATETIME)