SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM (
    SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, REVIEW_SCORE
    FROM REST_REVIEW RR
    JOIN REST_INFO RI ON RR.REST_ID = RI.REST_ID
    WHERE ADDRESS LIKE "서울%"
) AS T
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC