SELECT APNT_NO, PT_NAME, T.PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM (
    SELECT APNT_NO, PT_NO, MDDR_ID, APNT_YMD
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
    AND MCDP_CD = "CS"
    AND APNT_CNCL_YN = "N"
) AS T
JOIN PATIENT ON PATIENT.PT_NO = T.PT_NO
JOIN DOCTOR ON DOCTOR.DR_ID = T.MDDR_ID
ORDER BY APNT_YMD