SELECT RH.HISTORY_ID,TRUNCATE(
    (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1) 
    * C.DAILY_FEE 
    * (1 - IFNULL(DP.DISCOUNT_RATE / 100, 0)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
JOIN CAR_RENTAL_COMPANY_CAR C
ON RH.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON C.CAR_TYPE = DP.CAR_TYPE AND (
    (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 90 AND DP.DURATION_TYPE = '90일 이상') OR
    (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30 AND DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 < 90 AND DP.DURATION_TYPE = '30일 이상') OR
    (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 7 AND DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 < 30 AND DP.DURATION_TYPE = '7일 이상')
)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, RH.HISTORY_ID DESC;